spring.application.name=Smart Contact Manager


# mysql configurations
spring.datasource.name=scm2
spring.datasource.url=jdbc:mysql://localhost:3306/scm2
spring.datasource.username=root
spring.datasource.password=root

# jpa configurations
#1 spring.jpa.show-sql=true (show sql queries in console) (optional)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#3jpa give queries to db  (optional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#5create tables and schema automatic 
spring.jpa.hibernate.ddl-auto=update


#security configuration (set default)
# spring.security.user.name=jemish
# spring.security.user.password=jemish
# logging.level.org.springframework.security=DEBUG

# oauth2 client

# google cinfigure
# spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=1069300615381-3u59arl1ftjl88at94iua04dod3iu5p9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# github configure
# spring.security.oauth2.client.registration.github.client-name=github
spring.security.oauth2.client.registration.github.client-id=Iv23liMhwBYEBwgondqr
spring.security.oauth2.client.registration.github.client-secret=a79aad923d38fe415ec8aff625a1b1c215306a32
spring.security.oauth2.client.registration.github.scope=email,profile

# cloudinary configure
cloudinary.cloud.name=dyl2nuiqo
cloudinary.api.key=442965132648265
cloudinary.api.secret=P-Rv-0UkJ09ryF8CknXcaXyNlp4

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#email configurations