
spring.application.name=Smart Contact Manager

# mysql configurations
spring.datasource.name=scm2
spring.datasource.url=jdbc:mysql://localhost:3306/scm2
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# jpa configurations
#1 spring.jpa.show-sql=true (show sql queries in console) (optional)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#3jpa give queries to db  (optional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#5create tables and schema automatic 
spring.jpa.hibernate.ddl-auto=update
# show queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#security configuration (set default)
# spring.security.user.name=user
# spring.security.user.password=
# logging.level.org.springframework.security=DEBUG

# oauth2 client

# google cinfigure
# spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# github configure
# spring.security.oauth2.client.registration.github.client-name=github
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=email,profile

# cloudinary configure
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# email configurations

spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.domain_name=${MAIN_DOMAIN}
