spring.application.name=Smart Contact Manager


# mysql configurations
spring.datasource.name=scm2
spring.datasource.url=jdbc:mysql://localhost:3306/scm2
spring.datasource.username=root
spring.datasource.password=root

# jpa configurations
#1 spring.jpa.show-sql=true (show sql queries in console) (optional)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#3jpa give queries to db  (optional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#5create tables and schema automatic 
spring.jpa.hibernate.ddl-auto=update


#security configuration (set default)
# spring.security.user.name=jemish
# spring.security.user.password=jemish


logging.level.org.springframework.security=DEBUG

#email configurations